[package]
name = "getting-started-with-rust-lfel1002"
version = "0.1.0"

[[bin]]
name = "security01"

[[bin]]
name = "pizza"

[workspace.lint.clippy]
pedantic = "warn"

[dependencies]
regex = "1.0.0"
